# Generated by Django 5.1.7 on 2026-04-24 19:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBehaviorAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(db_index=True, max_length=64)),
                ('target_url', models.CharField(blank=True, default='', max_length=1024)),
                ('target_domain', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('action_payload', models.JSONField(blank=True, default=dict)),
                ('response_status', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_exception', models.BooleanField(db_index=True, default=False)),
                ('exception_message', models.CharField(blank=True, default='', max_length=512)),
                ('trace_detail', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_audit_logs', to='research_agent.agenttask')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
    ]
