# Generated by Django 5.1.7 on 2026-04-27 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_agent', '0002_agentbehaviorauditlog'),
        ('research_agent', '0002_session_owner_id'),
    ]

    operations = [
    ]
