# Generated by Django 5.1.7 on 2026-04-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_agent", "0003_merge_20260427_0108"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentbehaviorauditlog",
            name="actor_type",
            field=models.CharField(blank=True, db_index=True, default="system", max_length=32),
        ),
        migrations.AddField(
            model_name="agentbehaviorauditlog",
            name="policy_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="agentbehaviorauditlog",
            name="risk_level",
            field=models.CharField(blank=True, db_index=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="agentbehaviorauditlog",
            name="rule_hit",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="agentbehaviorauditlog",
            name="status",
            field=models.CharField(blank=True, db_index=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="agentbehaviorauditlog",
            name="step_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="agentbehaviorauditlog",
            name="tool_type",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="agentbehaviorauditlog",
            name="trace_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
    ]
