# Generated by Django 5.1.7 on 2026-04-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research_agent", "0004_agentbehaviorauditlog_v2_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAccessPolicyConfig",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "mode",
                    models.CharField(
                        choices=[("whitelist", "whitelist"), ("blacklist", "blacklist")],
                        db_index=True,
                        default="blacklist",
                        max_length=16,
                    ),
                ),
                ("policy_version", models.PositiveIntegerField(default=1)),
                ("updated_by", models.CharField(blank=True, default="", max_length=64)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SiteAccessRule",
            fields=[
                ("rule_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[("allow", "allow"), ("deny", "deny")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[("exact", "exact"), ("suffix", "suffix"), ("wildcard", "wildcard")],
                        db_index=True,
                        default="suffix",
                        max_length=16,
                    ),
                ),
                ("pattern", models.CharField(db_index=True, max_length=255)),
                ("priority", models.PositiveIntegerField(db_index=True, default=100)),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("created_by", models.CharField(blank=True, default="", max_length=64)),
                ("updated_by", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["priority", "rule_id"],
            },
        ),
    ]
