# Generated by Django 5.1.7 on 2025-03-29 11:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0036_uservisit"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperPosition",
            fields=[
                (
                    "pos_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "page_number",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "x",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "y",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperAnnotationCommentFirstLevel",
            fields=[
                (
                    "comment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField()),
                ("visibility", models.BooleanField(default=True)),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.user"
                    ),
                ),
                (
                    "like_by_user",
                    models.ManyToManyField(
                        blank=True,
                        related_name="annotation_liked_first_comments",
                        to="business.user",
                    ),
                ),
                (
                    "paper_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.paper"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperAnnotationCommentSecondLevel",
            fields=[
                (
                    "comment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField()),
                ("visibility", models.BooleanField(default=True)),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.user"
                    ),
                ),
                (
                    "like_by_user",
                    models.ManyToManyField(
                        blank=True,
                        related_name="annotation_liked_second_comments",
                        to="business.user",
                    ),
                ),
                (
                    "paper_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.paper"
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.paperannotationcommentfirstlevel",
                    ),
                ),
                (
                    "reply_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.paperannotationcommentsecondlevel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperNote",
            fields=[
                (
                    "note_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "note_type",
                    models.IntegerField(
                        choices=[(1, "Highlight"), (2, "Notes"), (3, "Summary")]
                    ),
                ),
                ("content", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.user"
                    ),
                ),
                (
                    "paper_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.paper"
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.paperposition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaperAnnotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "annotation_type",
                    models.IntegerField(choices=[(1, "Underline"), (2, "Postil")]),
                ),
                ("content", models.TextField(null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("visibility", models.BooleanField(default=True)),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.user"
                    ),
                ),
                (
                    "liked_by_user",
                    models.ManyToManyField(
                        blank=True, related_name="liked_annotations", to="business.user"
                    ),
                ),
                (
                    "paper_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.paper"
                    ),
                ),
                (
                    "position",
                    models.ManyToManyField(
                        blank=True,
                        related_name="annotations_position",
                        to="business.paperposition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserDocumentNote",
            fields=[
                (
                    "note_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "note_type",
                    models.IntegerField(
                        choices=[(1, "Highlight"), (2, "Notes"), (3, "Summary")]
                    ),
                ),
                ("content", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.user"
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.paperposition",
                    ),
                ),
                (
                    "user_document_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.userdocument",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
