# Generated by Django 5.1.7 on 2025-03-29 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0037_paperposition_paperannotationcommentfirstlevel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Glossary",
            fields=[
                (
                    "glossary_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="GlossaryTerm",
            fields=[
                (
                    "term_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("term", models.CharField(max_length=255)),
                ("translation", models.CharField(max_length=255)),
                (
                    "parent_glossary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="business.glossary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperTranslation",
            fields=[
                (
                    "translation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("result_path", models.CharField(max_length=255, unique=True)),
                (
                    "glossary",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.glossary",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_translations",
                        to="business.paper",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserDocumentTranslation",
            fields=[
                (
                    "translation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("result_path", models.CharField(max_length=255, unique=True)),
                (
                    "glossary",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.glossary",
                    ),
                ),
                (
                    "user_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_document_translations",
                        to="business.userdocument",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
