# Generated by Django 5.1.7 on 2025-03-30 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "business",
            "0039_autodeletedfirstcomment_autodeletedpaperannotation_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paperannotationcommentfirstlevel",
            name="paper_id",
        ),
        migrations.RemoveField(
            model_name="paperannotationcommentsecondlevel",
            name="paper_id",
        ),
        migrations.AddField(
            model_name="paperannotationcommentfirstlevel",
            name="annotation_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="business.paperannotation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paperannotationcommentsecondlevel",
            name="annotation_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="business.paperannotation",
            ),
            preserve_default=False,
        ),
    ]
