# Generated by Django 5.1.7 on 2025-04-06 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0040_remove_paperannotationcommentfirstlevel_paper_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperVisitRecent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_time", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.paper"
                    ),
                ),
            ],
        ),
    ]
