# Generated by Django 5.1.7 on 2025-04-06 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0041_papervisitrecent"),
    ]

    operations = [
        migrations.AddField(
            model_name="papertranslation",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="business.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userdocumenttranslation",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="business.user",
            ),
            preserve_default=False,
        ),
    ]
