# Generated by Django 5.1.7 on 2025-04-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0043_alter_papertranslation_result_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="papernote",
            name="position",
        ),
        migrations.RemoveField(
            model_name="userdocumentnote",
            name="position",
        ),
        migrations.AddField(
            model_name="papernote",
            name="position",
            field=models.ManyToManyField(
                blank=True,
                related_name="paper_notes_position",
                to="business.paperposition",
            ),
        ),
        migrations.AddField(
            model_name="userdocumentnote",
            name="position",
            field=models.ManyToManyField(
                blank=True,
                related_name="document_notes_position",
                to="business.paperposition",
            ),
        ),
    ]
