# Generated by Django 5.1.7 on 2025-04-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0044_remove_papernote_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservisit",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
