# Generated by Django 5.1.7 on 2025-04-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0045_alter_uservisit_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="papertranslation",
            name="task_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="papertranslation",
            name="task_status",
            field=models.IntegerField(
                choices=[(0, "Working"), (1, "Success"), (2, "Failed")], default=0
            ),
        ),
        migrations.AddField(
            model_name="userdocumenttranslation",
            name="task_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userdocumenttranslation",
            name="task_status",
            field=models.IntegerField(
                choices=[(0, "Working"), (1, "Success"), (2, "Failed")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="papertranslation",
            name="result_path",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userdocumenttranslation",
            name="result_path",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
