# Generated by Django 5.1.7 on 2025-05-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0046_papertranslation_task_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="papernote",
            name="content",
        ),
        migrations.RemoveField(
            model_name="papernote",
            name="note_type",
        ),
        migrations.RemoveField(
            model_name="userdocumentnote",
            name="content",
        ),
        migrations.RemoveField(
            model_name="userdocumentnote",
            name="note_type",
        ),
        migrations.AddField(
            model_name="papernote",
            name="contents",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="userdocumentnote",
            name="contents",
            field=models.JSONField(null=True),
        ),
    ]
