# Generated by Django 5.1.7 on 2025-05-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "business",
            "0047_remove_papernote_content_remove_papernote_note_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="papernote",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userdocumentnote",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
