# Generated by Django 5.1.7 on 2025-05-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0048_papernote_name_userdocumentnote_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="papernote",
            name="position",
        ),
        migrations.RemoveField(
            model_name="userdocumentnote",
            name="position",
        ),
    ]
