# Generated by Django 5.1.7 on 2025-05-04 18:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0049_remove_papernote_position_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummaryGenerateSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Initial"),
                            (1, "Waiting AI"),
                            (2, "Waiting User"),
                            (3, "Done"),
                        ],
                        default=0,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now=True)),
                ("content_buffer", models.TextField(default="")),
            ],
        ),
    ]
