# Generated by Django 5.1.7 on 2025-05-05 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0050_summarygeneratesession"),
    ]

    operations = [
        migrations.AddField(
            model_name="summarygeneratesession",
            name="paper_ids",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="summarygeneratesession",
            name="search_record",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summary_session",
                to="business.searchrecord",
            ),
            preserve_default=False,
        ),
    ]
