# Generated by Django 5.1.7 on 2025-05-05 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0051_summarygeneratesession_paper_ids_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperAnnotationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.user"
                    ),
                ),
                (
                    "liked_by_user",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_annotations_new",
                        to="business.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperAnnotationComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.user"
                    ),
                ),
                (
                    "liked_by_user",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_comments_new",
                        to="business.user",
                    ),
                ),
                (
                    "annotation_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.paperannotationitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperAnnotationNew",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("passage_content", models.TextField()),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.paper"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paperannotationitem",
            name="annotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="business.paperannotationnew",
            ),
        ),
    ]
