# Generated by Django 5.1.7 on 2025-05-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0052_paperannotationitem_paperannotationcomment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="papernote",
            name="markdown",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="userdocumentnote",
            name="markdown",
            field=models.TextField(default="", null=True),
        ),
    ]
