# Generated by Django 5.1.7 on 2025-05-27 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0053_papernote_markdown_userdocumentnote_markdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummaryDialogStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("conversation", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("steps", models.IntegerField(default=0)),
                ("paper_info", models.JSONField(default=list)),
                ("tmp_kb_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.summaryreport",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
