# Generated by Django 5.1.7 on 2025-05-28 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0055_vectorsearchstorage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paperannotationnew",
            name="passage_content",
        ),
        migrations.AddField(
            model_name="paperannotationcomment",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="paperannotationitem",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="paperannotationnew",
            name="position",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PaperAnnotationSubComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("content", models.TextField()),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="business.user"
                    ),
                ),
                (
                    "liked_by_user",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_sub_comments_new",
                        to="business.user",
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.paperannotationcomment",
                    ),
                ),
            ],
        ),
    ]
