# Generated by Django 5.1.7 on 2025-05-28 20:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0056_remove_paperannotationnew_passage_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractreport",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
