# Generated by Django 5.1.7 on 2025-05-31 14:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0057_abstractreport_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstlevelcomment",
            name="check_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="firstlevelcomment",
            name="under_pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paperannotationcomment",
            name="check_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paperannotationcomment",
            name="under_pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paperannotationcomment",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paperannotationitem",
            name="check_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paperannotationitem",
            name="under_pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paperannotationitem",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paperannotationsubcomment",
            name="check_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paperannotationsubcomment",
            name="under_pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paperannotationsubcomment",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="secondlevelcomment",
            name="check_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="secondlevelcomment",
            name="under_pending",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="AutoDeletedAnnotationCommentNew",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("reverted", models.BooleanField(default=False)),
                ("reason", models.TextField(null=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.paperannotationcomment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AutoDeletedAnnotationNew",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("reverted", models.BooleanField(default=False)),
                ("reason", models.TextField(null=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.paperannotationitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AutoDeletedAnnotationSubCommentNew",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("reverted", models.BooleanField(default=False)),
                ("reason", models.TextField(null=True)),
                (
                    "sub_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_comments",
                        to="business.paperannotationsubcomment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
