# Generated by Django 5.1.7 on 2025-06-02 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0058_firstlevelcomment_check_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DialogSearchStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("conversation", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "search_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="business.searchrecord",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
