# Generated by Django 5.1.7 on 2026-04-19 01:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0059_dialogsearchstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessFrequencyRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('deep_research', 'Deep Research 任务'), ('ai_chat', 'AI 对话（研读/调研助手）'), ('summary', '综述报告生成'), ('export', '报告批量导出')], max_length=32, unique=True, verbose_name='功能类型')),
                ('window', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], default='daily', max_length=16, verbose_name='统计窗口')),
                ('max_count', models.IntegerField(default=10, verbose_name='最大次数（-1=不限）')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=64, verbose_name='最后修改人')),
            ],
            options={
                'verbose_name': '访问频次规则',
                'db_table': 'access_frequency_rule',
            },
        ),
        migrations.CreateModel(
            name='DeepResearchTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(verbose_name='研究问题')),
                ('max_rounds', models.IntegerField(default=3, verbose_name='最大迭代轮数')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('queued', '排队中'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('aborted', '用户主动中止'), ('admin_stopped', '管理员强制中断'), ('violation_pending', '合规审核中'), ('needs_review', '待人工审核'), ('archived', '已归档')], db_index=True, default='pending', max_length=24, verbose_name='状态')),
                ('current_phase', models.CharField(blank=True, choices=[('planning', '规划'), ('searching', '检索'), ('reading', '阅读'), ('reflecting', '反思'), ('writing', '生成报告')], max_length=16, null=True, verbose_name='当前阶段')),
                ('progress', models.IntegerField(default=0, verbose_name='进度 0-100')),
                ('step_summary', models.CharField(blank=True, default='', max_length=512, verbose_name='最新步骤摘要')),
                ('token_used_total', models.IntegerField(default=0, verbose_name='累计消耗 Token')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('report', models.JSONField(blank=True, null=True, verbose_name='结构化报告 JSON')),
                ('citation_coverage', models.FloatField(blank=True, null=True, verbose_name='循证覆盖率')),
                ('admin_stop_flag', models.BooleanField(default=False, help_text='管理员置 True 后，编排器下轮检查时安全退出', verbose_name='强制中断信号')),
                ('output_suppressed', models.BooleanField(default=False, help_text='True 时用户端获取报告接口返回 403', verbose_name='屏蔽报告输出')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('file_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dr_tasks', to='business.filereading')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dr_tasks', to='business.user')),
            ],
            options={
                'verbose_name': 'Deep Research 任务',
                'db_table': 'deep_research_task',
            },
        ),
        migrations.CreateModel(
            name='DeepResearchAuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('force_stop', '强制中断'), ('suppress_output', '屏蔽输出'), ('unsuppress_output', '恢复输出'), ('view_trace', '查看轨迹')], max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dr_audit_logs', to='business.admin')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='business.deepresearchtask')),
            ],
            options={
                'verbose_name': 'DR 管理操作审计日志',
                'db_table': 'deep_research_audit_log',
            },
        ),
        migrations.CreateModel(
            name='DeepResearchStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(verbose_name='步骤序号（从 1 开始）')),
                ('phase', models.CharField(max_length=16, verbose_name='所属阶段')),
                ('action', models.CharField(max_length=64, verbose_name='动作描述')),
                ('summary', models.TextField(blank=True, default='', verbose_name='步骤摘要')),
                ('token_used', models.IntegerField(default=0, verbose_name='本步骤 Token 消耗')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='business.deepresearchtask')),
            ],
            options={
                'verbose_name': 'Deep Research 执行步骤',
                'db_table': 'deep_research_step',
                'ordering': ['seq'],
                'unique_together': {('task', 'seq')},
            },
        ),
        migrations.CreateModel(
            name='FeatureAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(db_index=True, max_length=32, verbose_name='功能类型')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('allowed', '放行'), ('rejected', '因超限被拒')], max_length=16)),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='business.user')),
            ],
            options={
                'verbose_name': '功能访问日志',
                'db_table': 'feature_access_log',
                'indexes': [models.Index(fields=['feature', 'accessed_at'], name='feature_acc_feature_aa7449_idx'), models.Index(fields=['user', 'feature', 'accessed_at'], name='feature_acc_user_id_cff600_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAccessQuotaOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('deep_research', 'Deep Research 任务'), ('ai_chat', 'AI 对话（研读/调研助手）'), ('summary', '综述报告生成'), ('export', '报告批量导出')], max_length=32, verbose_name='功能类型')),
                ('max_count', models.IntegerField(default=-1, verbose_name='覆盖次数上限')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=64, verbose_name='操作人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_overrides', to='business.user')),
            ],
            options={
                'verbose_name': '用户配额覆盖',
                'db_table': 'user_access_quota_override',
                'unique_together': {('user', 'feature')},
            },
        ),
    ]
