# Generated by Django 5.1.7 on 2026-04-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0060_accessfrequencyrule_deepresearchtask_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deepresearchtask",
            name="latest_violation_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最近一次违规时间"
            ),
        ),
        migrations.AddField(
            model_name="deepresearchtask",
            name="latest_violation_phase",
            field=models.CharField(
                blank=True, default="", max_length=16, verbose_name="最近一次违规阶段"
            ),
        ),
        migrations.AddField(
            model_name="deepresearchtask",
            name="latest_violation_reason",
            field=models.CharField(
                blank=True, default="", max_length=512, verbose_name="最近一次违规原因"
            ),
        ),
        migrations.AddField(
            model_name="deepresearchtask",
            name="latest_violation_source",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="最近一次违规来源"
            ),
        ),
        migrations.AddField(
            model_name="deepresearchtask",
            name="report_compliance_hash",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="报告合规扫描哈希"
            ),
        ),
        migrations.AddField(
            model_name="deepresearchtask",
            name="violation_count",
            field=models.IntegerField(default=0, verbose_name="违规命中次数"),
        ),
        migrations.AlterField(
            model_name="deepresearchauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("force_stop", "强制中断"),
                    ("suppress_output", "屏蔽输出"),
                    ("unsuppress_output", "恢复输出"),
                    ("view_trace", "查看轨迹"),
                    ("auto_violation", "自动违规命中"),
                ],
                max_length=32,
            ),
        ),
    ]
