# Generated by Django 5.1.7 on 2026-04-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0061_deepresearchtask_latest_violation_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeepResearchTaskArchive",
            fields=[
                ("archive_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "terminal_status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("queued", "排队中"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("aborted", "用户主动中止"),
                            ("admin_stopped", "管理员强制中断"),
                            ("violation_pending", "合规审核中"),
                            ("needs_review", "待人工审核"),
                            ("archived", "已归档"),
                        ],
                        max_length=24,
                        verbose_name="归档前终态",
                    ),
                ),
                ("archived_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "report_payload",
                    models.JSONField(
                        blank=True, null=True, verbose_name="归档报告内容"
                    ),
                ),
                (
                    "citation_traces",
                    models.JSONField(
                        blank=True, default=list, verbose_name="引用溯源信息"
                    ),
                ),
                (
                    "resource_audit_report",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="资源消耗审计报告"
                    ),
                ),
                (
                    "lifecycle_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="任务生命周期快照"
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_record",
                        to="business.deepresearchtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "DR 任务归档",
                "db_table": "deep_research_task_archive",
            },
        ),
    ]
