# Generated by Django 5.1.7 on 2026-04-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0062_deepresearchtaskarchive"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessConcurrencyRule",
            fields=[
                ("rule_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("deep_research", "Deep Research 任务"),
                            ("ai_chat", "AI 对话（研读/调研助手）"),
                            ("summary", "综述报告生成"),
                            ("export", "报告批量导出"),
                        ],
                        max_length=32,
                        unique=True,
                        verbose_name="功能类型",
                    ),
                ),
                (
                    "max_global_running",
                    models.IntegerField(default=3, verbose_name="全局运行并发上限（-1=不限）"),
                ),
                (
                    "max_user_running",
                    models.IntegerField(default=1, verbose_name="单用户运行并发上限（-1=不限）"),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="描述")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="最后修改人"),
                ),
            ],
            options={
                "verbose_name": "并发规则",
                "db_table": "access_concurrency_rule",
            },
        ),
        migrations.CreateModel(
            name="UserAccessConcurrencyOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("deep_research", "Deep Research 任务"),
                            ("ai_chat", "AI 对话（研读/调研助手）"),
                            ("summary", "综述报告生成"),
                            ("export", "报告批量导出"),
                        ],
                        max_length=32,
                        verbose_name="功能类型",
                    ),
                ),
                (
                    "max_user_running",
                    models.IntegerField(default=-1, verbose_name="用户并发上限（-1=不限）"),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255, verbose_name="原因")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="操作人"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concurrency_overrides",
                        to="business.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户并发覆盖",
                "db_table": "user_access_concurrency_override",
                "unique_together": {("user", "feature")},
            },
        ),
    ]
