"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from decouple import RepositoryEnv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load secrets from env file
# profile = os.getenv("EPP_BACKEND_PROFILE")
DEBUG = False  # Switch to False in production
config = RepositoryEnv(str(BASE_DIR / "development.env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config["SECRET_KEY"]

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "business",
    "research_agent",
    "django_crontab",
    "background_task",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# 设置跨域 SESSION 配置，本地测试时需要 SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "None"
CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_HTTPONLY = True
# 设置 iframe 跨域
X_FRAME_OPTIONS = "SAMEORIGIN"

# 配置为 true 会出问题
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://localhost:5173",
    "http://127.0.0.1:8080",
    "http://localhost:10516",
    "http://127.0.0.1:10516",
    "http://epp.swkfk.top",
    "http://admin.swkfk.top",
]

# 非调试模式，添加前端的地址
# if not DEBUG:
#     CORS_ALLOWED_ORIGINS += config["FRONTEND_ORIGIN"]

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

CORS_ALLOW_HEADERS = (
    "XMLHttpRequest",
    "X_FILENAME",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "Pragma",
)

ROOT_URLCONF = "backend.urls"

RESOURCE_PATH = os.path.join(BASE_DIR, "resource")

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        key: config[f"DB_{key}"]
        for key in ["ENGINE", "NAME", "USER", "PASSWORD", "HOST", "PORT"]
        if f"DB_{key}" in config
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]

ADMIN_USERNAME = config["ADMIN_USERNAME"]
ADMIN_PASSWORD = config["ADMIN_PASSWORD"]

AUTHENTICATION_BACKENDS = [
    "business.admin_site.CustomAdminBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "/resource/"
MEDIA_ROOT = os.path.join(BASE_DIR, "resource")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

USER_AVATARS_PATH = "resource/uploads/users/avatars"  # 用户头像相对路径
USER_DOCUMENTS_PATH = "resource/uploads/users/documents"  # 用户上传文件路径
USER_REPORTS_PATH = "resource/database/users/reports"  # 用户生成报告路径
USER_SEARCH_CONSERVATION_PATH = (
    "resource/database/users/conversation/search"  # 调研助手对话文件路径
)
USER_READ_CONSERVATION_PATH = (
    "resource/database/users/conversation/read"  # 论文研读助手对话文件路径
)
USER_READ_MAP_PATH = (
    "resource/database/users/conversation/read/file_reading_2_tmp_kb_id_map.json"
)
USER_SEARCH_MAP_PATH = "resource/database/users/conversation/search/search_record_2_tmp_kb_id_map.json"  # 用户搜索记录与知识库 id 映射
PAPERS_PATH = "resource/database/papers/"  # 数据库论文路径
BATCH_DOWNLOAD_PATH = "resource/database/users/batch_download"  # 批量下载文件路径
PAPERS_ABS_PATH = "resource/database/papers/abs/"  # 数据库论文摘要路径

PAPERS_URL = "resource/database/papers/"  # 数据库论文本地 URL
BATCH_DOWNLOAD_URL = "/resource/database/users/batch_download/"  # 批量下载文件本地 URL
USER_DOCUMENTS_URL = "/resource/uploads/users/documents/"  # 用户上传文件本地 URL
CACHE_PATH = "/cache/"  # 缓存路径

MAX_Similarity = 0.8  # 最大相似度，介于 -1 和 1 之间，不确定

# 远程部署模型地址
REMOTE_CHAT_CHAT_PATH = config["REMOTE_CHAT_CHAT_PATH"]


def __set_model_url(port: int) -> str:
    return f"{REMOTE_CHAT_CHAT_PATH}:{port}"


REMOTE_MANAGER_PATH = __set_model_url(config["CHAT_CHAT_MANAGER_PORT"])
# 远程模型部署开放的 API 接口
REMOTE_MODEL_BASE_PATH = __set_model_url(config["MODEL_BASE_PORT"])
# 使用 openai 流式接口调用 glm3 大模型，不附带知识库
REMOTE_CHATCHAT_GLM3_OPENAI_PATH = __set_model_url(config["GLM3_OPENAI_PORT"])
REMOTE_CHAT_CHAT_GLM_PATH = __set_model_url(config["CHAT_GLM_PORT"])

# 语义检索相关
VECTOR_DIM = 1024
LOCAL_VECTOR_DATABASE_PATH = "resource/vector_database_for_search/"
LOCAL_FAISS_NAME = "paper_index.faiss"
LOCAL_METADATA_NAME = "paper_metadata.pkl"

WKHTMLTOPDF_PATH = config["WKHTMLTOPDF_PATH"]

# 文献翻译
SIMPLIFY_TRANS_KEY = config["SIMPLIFY_TRANS_KEY"]

# 评论校验
CENSOR_API_KEY = config["CENSOR_API_KEY"]
CENSOR_SECRET_KEY = config["CENSOR_SECRET_KEY"]

# deepseek
DEEPSEEK_API_KEY = config["DEEPSEEK_API_KEY"]

# CRONTAB_COMMAND_PREFIX = f"cd {BASE_DIR}"
CRONJOBS = [
    # (
    #     "* * * * *",
    #     "django.core.management.call_command",
    #     ["process_tasks"],
    #     {"duration": 60},
    #     ">> /tmp/django-epp-cron.log 2>&1",
    # ),
    (
        "*/3 * * * *",
        "business.models.paper_visit_recent.PaperVisitRecent.clear_three_days",
    ),
]

JWT_SECRET_KEY = config["JWT_SECRET_KEY"]

# 科研智能助手：Mock 步骤间隔（秒），测试可 override 为 0
RESEARCH_AGENT_MOCK_DELAY = (
    float(config["RESEARCH_AGENT_MOCK_DELAY"])
    if "RESEARCH_AGENT_MOCK_DELAY" in config
    else 0.08
)
# 出站 HTTP 允许的主机名（逗号分隔），详见 docs/research-agent/RISKS_AND_ASSUMPTIONS.md
RA_ALLOWED_HOSTS = [
    h.strip()
    for h in (config["RA_ALLOWED_HOSTS"] if "RA_ALLOWED_HOSTS" in config else "").split(
        ","
    )
    if h.strip()
]

# Minio
MINIO_ACCESS_KEY = config["MINIO_ACCESS_KEY"]
MINIO_SECRET_KEY = config["MINIO_SECRET_KEY"]
MINIO_ENDPOINT = config["MINIO_ENDPOINT"]

# Google Search
TAVILY_API_KEY = config["TAVILY_API_KEY"]
